# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.supportedFilesystems = ["ntfs"];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/dd2eb073-5e7e-4296-bc94-b47f881d4519";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/40B0-943A";
    fsType = "vfat";
  };

  # fileSystems."/home/user/files" = {
  #   device = "/dev/disk/by-uuid/2523b8da-8f54-4aba-8a37-2a95ddf4d088";
  #   fsType = "ntfs-3g";
  #   options = ["rw" "uid=100"];
  # };

  # fileSystems."/home/user/datastore" = {
  #   device = "/dev/disk/by-uuid/67286d90-f520-43ae-9922-742f1afb9094";
  #   fsType = "ntfs-3g";
  #   options = ["rw" "uid=100"];
  # };

  swapDevices = [
    {device = "/dev/disk/by-uuid/1d0c1be9-6098-45f0-a50c-8487dc2236a7";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
