[package]
name = "youtube-transcribe"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
directories = "6.0.0"
futures = "0.3"
gio = "0.21.2"
glib = "0.21.3"
glib-macros = "0.21.2"
gtk4 = { version = "0.10.1", features = ["v4_10"] }
libadwaita = { version = "0.8.0", features = ["v1_5"] }
once_cell = "1.21.3"
reqwest = { version = "0.12.23", features = ["blocking", "rustls-tls"] }
thiserror = "2.0.16"
uuid = { version = "1.18.1", features = ["v4"] }
