name: Build and cache NixOS system

on:
  push:
    paths:
      - "flake.lock"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: experimental-features = nix-command flakes

      - name: Authenticate with Cachix
        uses: cachix/cachix-action@v15
        with:
          name: joshua256 # Replace with your cache name
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          push: true # Allows pushing to the cache

      - name: Build NixOS system
        run: nix build .#nixos-surface
        # ^ Adjust flake reference to match your configuration path

      # Optionally, you can push more paths if needed (e.g., other derivations)
      # - run: cachix push my-cachix-cache $(nix path-info .#nixosConfigurations.myLaptop.config.system)
