name: Build and cache NixOS system

on:
  push:
    paths:
      - "flake.lock"

  workflow_dispatch:

jobs:
  build-and-push-kernels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device:
          - nixos-desktop
          - nixos-surface

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          install_url: https://nixos.org/nix/install

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: joshua256 # Replace with your Cachix cache name
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build Kernel for ${{ matrix.device }}
        run: |
          nix build .#nixosConfigurations.${{ matrix.device }}.config.system.build.kernel
          echo "Built kernel for ${{ matrix.device }}"

      - name: Push Kernel to Cachix for ${{ matrix.device }}
        run: |
          cachix push joshua256 ./result
          echo "Pushed kernel for ${{ matrix.device }} to Cachix"

      # Optional: Clean up the Nix store symlink
      - name: Clean up Nix store symlink
        run: rm -rf ./result
